## Prediction Using Support Vector Machines (SVM)
## Radial basis function kernel (RBF)

In [1]:
## Import Libraries
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn import metrics

#### Load dataset

In [2]:
url = "FINAL Data.csv"
df = pd.read_csv(url)
include = [ 'Age', 'Gender', 'Religon', 'Race', 'Nature Of Occupation' ,
           'Civil Status' ,'Education Level' ,'Reason' ,'Lifetime Psychiatric Hospitalizations' ,
           'Past Suicide Attempts' ,'Any suicidal thoughts mentioned' ,'Self-Injurious Behaviour' ,
           'Psychiatric Disorders' ,'Past Illnesses' ,'Alcohol/ drug Consumption','Anger',
           'Sleep Problem', 'Social Iscolation', 'Sad/ Weary' , 'Humilated', 'Not Suicide(0)/Suicide(1)']  # Except the year, all the features are taken 
df1 = df[include]
print(df1.head(20))
print(df1.describe())

    Age Gender    Religon       Race  \
0    30      F   Buddhist  Sinhalese   
1    91      F      Islam     Muslim   
2    85      M   Buddhist  Sinhalese   
3    87      M   Buddhist  Sinhalese   
4    59      F   Buddhist  Sinhalese   
5    31      M   Buddhist  Sinhalese   
6    75      F  Christian     Burger   
7    47      M   Buddhist  Sinhalese   
8    58      F  Christian     Burger   
9    36      F      Hindu      Tamil   
10   87      M   Buddhist  Sinhalese   
11   73      F  Christian     Burger   
12   44      M   Buddhist  Sinhalese   
13   62      M   Buddhist  Sinhalese   
14   21      F      Hindu      Tamil   
15   70      M   Buddhist  Sinhalese   
16   68      M      Hindu      Tamil   
17   43      F   Buddhist  Sinhalese   
18   16      M      Other     Burger   
19   35      M      Hindu      Tamil   

                                 Nature Of Occupation Civil Status  \
0   Administrative Executive Managerial & related ...    Unmarried   
1                  

#### Data Preprocessing


In [3]:
categoricals = []
for col, col_type in df1.dtypes.iteritems():
     if col_type == 'O':
          categoricals.append(col)
     else:
          df1[col].fillna(0, inplace=True)

c:\users\dinis\pycharmprojects\suicide-risk-predictor\venv\lib\site-packages\pandas\core\generic.py:6245: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)


#### LabelEncoder

In [4]:
category_col =['Gender', 'Religon', 'Race', 'Nature Of Occupation' ,
           'Civil Status' ,'Education Level' ,'Reason' ,
           'Psychiatric Disorders' ,'Past Illnesses' ,'Alcohol/ drug Consumption'] 
labelEncoder = preprocessing.LabelEncoder()
mapping_dict={}
for col in category_col:
    df1[col] = labelEncoder.fit_transform(df1[col])
    le_name_mapping = dict(zip(labelEncoder.classes_, labelEncoder.transform(labelEncoder.classes_)))
    mapping_dict[col]=le_name_mapping
print(df1.head(20))



    Age  Gender  Religon  Race  Nature Of Occupation  Civil Status  \
0    30       0        0     3                     0             2   
1    91       0        3     1                     8             1   
2    85       1        0     3                     9             1   
3    87       1        0     3                    12             1   
4    59       0        0     3                     4             2   
5    31       1        0     3                     1             2   
6    75       0        1     0                     2             0   
7    47       1        0     3                    12             1   
8    58       0        1     0                     2             2   
9    36       0        2     4                     2             3   
10   87       1        0     3                    12             1   
11   73       0        1     0                     3             3   
12   44       1        0     3                     1             1   
13   62       1     

c:\users\dinis\pycharmprojects\suicide-risk-predictor\venv\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys


##### Split the dataset

In [5]:
X = df1.values[:, 0:20]
Y = df1.values[:,20]
print(X)
print(Y)

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=109)  # 70% training and 30% testing

[[30  0  0 ...  0  0  0]
 [91  0  3 ...  0  0  0]
 [85  1  0 ...  0  0  0]
 ...
 [15  1  0 ...  0  1  1]
 [75  0  3 ...  0  0  0]
 [56  0  0 ...  1  1  0]]
[0 0 0 1 0 1 0 1 0 0 1 0 1 1 0 1 0 1 0 1 0 1 1 1 0 0 1 1 1 1 0 1 0 1 0 0 1
 1 1 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 1 0 0 1 0 1 1 0 1 1 1 0 1 0 1 0 1 1
 1 0 0 0 0 0 1 1 0 1 0 0 0 1 1 0 0 1 0 0 1 1 0 0 1 0 0 1 1 0 0 1 1 0 0 0 0
 0 0 0 1 0 0 1 0 1 0 0 1 1 1 1 0 1 0 0 0 0 0 1 1 1 0 1 0 0 1 1 0 1 1 0 0 1
 0 0 0 0 0 0 1 0 0 1 1 1 1 0 0 1 0 1 1 0 1 0 0 0 1 1 1 0 0 1 1 0 1 0 0 1 1
 1 0 0 1 0 1 1 0 1 1 0 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 0 0 0 1 0 0 0 1 0 0
 1 0 1 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 0 0 1 0 0 0 1 1 0 1 1 1 1 1 1 1
 0 0 1 1 0 1 0 0 1 0 0 1 0 1 1 1 0 0 0 0 1 0 0 1 0 1 1 1 0 0 1 1 1 1 0 1 1
 1 1 1 1 1 0 1 0 0 1 0 0 1 1 1 1 1 1 1 1 0 1 0 0 0 1 0 1 1 0 1 1 1 1 1 1 1
 1 1 0 0 0 0 1 0 1 1 1 0 1 1 1 0 1 1 0 1 1 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1
 0 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 0 0 1 0 0 1 1 1 0 1 1 1 1 0 1 1 0 0 1 0 0
 0 0 0 1 0 1 1 0 0 

#### Model Generation

In [6]:
#Importing the svm model
from sklearn import svm

#Build a svm Classifier
clf = svm.SVC(kernel='rbf') # polynomial Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)


#### Finding the accuracy

In [9]:
print("Accuracy from SVM(RBF) :",metrics.accuracy_score(y_test, y_pred))

Accuracy from SVM(RBF) : 0.7966666666666666


#### Precision and Recall

In [10]:
print("Precision from SVM(RBF):",metrics.precision_score(y_test, y_pred))
print("Recall from SVM(RBF):",metrics.recall_score(y_test, y_pred))


Precision from SVM(RBF): 0.7514450867052023
Recall from SVM(RBF): 0.8783783783783784
